### PR TITLE
Constrain rgeo to compatible version. Clean up and document to make it easier to run the tests.

### PR DESCRIPTION
**Pull request by dschweisguth**
The only substantial change is the rgeo version restriction. Hoping that makes sense to everyone.

I considered adding that restriction to the gemspec, but there is at least one project in the wild (mine) which is successfully using rgeo 0.6.0 with version 0.5.0 of this gem and it seems wrong to disallow working combinations of versions (even if they're only working because only parts of the gems involved are being exercised).

### CODE REVIEW

**Comment by dschweisguth** [comment]
@januszm please have a look!

**Comment by dschweisguth** [comment]
I fixed the tests for later versions of rgeo, so I'll close this and open a new PR.

**Comment by dschweisguth** [comment]
I fixed the tests for later versions of rgeo, so I'll close this and open a new PR.

**Comment by januszm** [comment]
Thanks @dschweisguth and sorry about late response but I'm swamped at the moment.

**Pull request closed without merging**
