### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by dschweisguth**
- Use Ruby 1.9 hash syntax where possible
- Remove --- and ; from file headers
- Remove excess whitespace
- Use spaces inside {} around one-line blocks and hashes

I
- cherry-picked https://github.com/rgeo/activerecord-mysql2spatial-adapter/tree/code_cleanup onto current master
- fixed a few more =>
- fixed spacing in one-line blocks and hashes
- changed new gem version from 0.6.0 to 0.5.2, since the only user-visible change is the removal of => from the README

Lots more things could be cleaned up, but it would be nice to merge this change and move on.

### CODE REVIEW

**Comment by dschweisguth** [comment]
@januszm clearing the decks ...

**Comment by januszm** [comment]
OK, good catch about the version number

**Comment by januszm** [comment]
@dschweisguth could you also cherry-pick 3971d4a752c79414932799349bf7646359285232 ?

It removes the dev dependency on the debugger (pry).

I'd also drop the release date from History.rdoc, it'll be problematic to maintain it this way, and we have timestamps in commit data anyway.

**Comment by dschweisguth** [comment]
@januszm done

**Comment by januszm** [comment]
Thanks!

**Pull request merged**
