### PR TITLE
Compatibility with ActiveRecord 4.1 and Rgeo 1.1

### PR DESCRIPTION
**Pull request by januszm**
Since the latest RGeo version that is compatible with Rails 4.1 (ActiveRecord 4.1.x) is 1.1.0 I locked the rgeo-activerecord version at 1.x

All tests pass, spatial indexes can be created only for MyISAM tables in MySQL <= 5.6.

It seems that this gem asks for some more cleanup and refactoring, see activerecord-postgis-adapter for reference (looks much cleaner).

I've also created a pull request that fixes the problem with missing statement parts for index definitions and the SpatialIndexDefinition struct in rgeo-activerecord v1.1. (https://github.com/rgeo/rgeo-activerecord/pull/24)

### CODE REVIEW

**Comment by januszm** [comment]
@teeparham - I'd like to get in touch with you regarding this gem. I'm interested in making it compatible with Rails 4.1 first, then most probably with Rails 4.2 and refactoring the code.

**Comment by teeparham** [comment]
@januszm thanks for doing this work. 

I had made @benatkin the maintainer of the gem (see #13), but it doesn't look like he's done anything, so if you're interested, you can take it.

**Comment by januszm** [comment]
Did @benatkin say anything about his plans? If no, then sure @teeparham please make me the maintainer.

**Comment by teeparham** [comment]
@januszm I added you to the rgeo-mysql team. Send me your email associated with your rubygems account & I'll add you as a gem owner so you can release this once it's ready to go. (My email is in https://github.com/rgeo/rgeo-activerecord/blob/master/rgeo-activerecord.gemspec)

**Comment by benatkin** [comment]
@teeparham @januszm I was using this at work which was how I got interested, but we wound up using postgres instead. I've removed myself from the team. Thanks!

**Comment by teeparham** [comment]
@benatkin thanks for the update

**Comment by januszm** [comment]
@teeparham my account name in rubygems is the same one as here. As for the email address, just put dot before 'm' and it's at gmail.com ;)

**Comment by januszm** [comment]
Updated, all tests pass. I've also tested spatial index creation in real Rails application, looks good. Should work well with Rails up to 4.1 (it also means that it's compatible with rgeo-activerecord 1.x only, see https://github.com/rgeo/rgeo-activerecord#installation)

**Comment by januszm** [comment]
I guess the next step is to provide compatibility with latest rgeo-activerecord and Rails 4.2. It would mean that the adapter should implement features removed from rgeo-activerecord since commit 219d2aff325deec1b7a6435295c27c67866f24b3

**Pull request merged**
